<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServicoMLBEntidades.Application\ServicoMLBEntidades.Application.csproj" />
    <ProjectReference Include="..\ServicoMLBEntidades.Infrastructure\ServicoMLBEntidades.Infrastructure.csproj" />
  </ItemGroup>

</Project>
